language: python
# services:
  # - go
  # - singularity
python:
  # - "2.7"
  # - "3.4"
  - "3.5"
  - "3.7"
  
cache:
  directories: 
    - $HOME/.pip
    - $HOME/.singularity
    - /opt/singularity
    # - $HOME/virtualenv ### too big
before_install:
  - sudo apt-get update
  - sudo apt install -y graphviz
  - curl -sL https://raw.githubusercontent.com/shouldsee/spiper/master/scripts/install_singular.sh | bash -s $HOME/.local
  - singularity --verbose --debug exec docker://python:2.7.17-alpine python -V
  - pip install spiper@https://github.com/shouldsee/spiper/tarball/0.0.8
install:
  - echo pass
script:
  - python -V
  - pip install .
  - bash run.sh python
  # - ls -lhtr /deps/*
  # - tree /deps



# before_install:
# - docker pull carlad/sinatra
# - docker run -d -p 127.0.0.1:80:4567 carlad/sinatra /bin/sh -c "cd /root/sinatra; bundle exec foreman start;"
# - docker ps -a
# - docker run carlad/sinatra /bin/sh -c "cd /root/sinatra; bundle exec rake test"

# script:
# - bundle exec rake test  
# docker://quay.io/singularity/singularity:v3.5.3-slim
